name: action test
on: [workflow_dispatch, workflow_call]

permissions: read-all

jobs:
  prepare-matrix:
    name: Prepare Matrix
    runs-on: ubuntu-latest
    outputs:
      payload-pull-request: ${{ steps.create-pull-request-payload.outputs.payload }}
      payload-all: ${{steps.create-all-payload.outputs.payload}}
      payload-trunk-merge: ${{steps.create-trunk-merge-payload.outputs.payload}}
    steps:
      - name: Create Matrix Variable Pull Request
        id: create-pull-request-payload
        run:
          echo "TEST_PULL_REQUEST_PAYLOAD"="$(</action_tests/pull_request_test_payload.json)" >>
          $GITHUB_OUTPUT
      - name: Create Matrix Variable All
        id: create-all-payload
        run: echo "TEST_ALL_PAYLOAD"="$(</action_tests/all_test_payload.json)" >> $GITHUB_OUTPUT
      - name: Create Matrix Variable Merge
        id: create-trunk-merge-payload
        run:
          echo "TEST_TRUNK_MERGE_PAYLOAD"="$(</action_tests/trunk_merge_test_payload.json)" >>
          $GITHUB_OUTPUT

  action_tests:
    needs: prepare-matrix
    name: ${{ matrix.description }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - description: pull-request-action-test
            payload: ${{ needs.prepare-matrix.outputs.payload-pull-request }}
          - description: trunk-merge-action-test
            payload: ${{ needs.prepare-matrix.outputs.payload-all }}
          - description: all-action-test
            payload: ${{ needs.prepare-matrix.outputs.payload-trunk-merge }}

    steps:
      - name: Checkout trunk-action
        uses: actions/checkout@v3
        with:
          path: local-action

      - name: Craft TEST_GITHUB_EVENT_PATH
        shell: bash
        # GITHUB_EVENT_PATH is the env var of path to file on runner that contains full webhook payload.
        # we are replacing it with TEST_GITHUB_EVENT_PATH so we read our predefined payload for test cases.
        run: |
          TEST_GITHUB_EVENT_PATH=$(mktemp)
          cat >> $TEST_GITHUB_EVENT_PATH <<EOF
          ${{matrix.payload}}
          EOF
          echo "TEST_GITHUB_EVENT_PATH=TEST_GITHUB_EVENT_PATH" >>$GITHUB_ENV

      - name: Run trunk-action for ${{matrix.description}}
        id: trunk
        uses: ./local-action/
        with:
          check-mode: payload
        continue-on-error: true

      - name: debug
        shell: bash
        run: |
          ls local-action
          pwd
          ls
          echo "$TRUNK_PATH"
          echo "${{matrix.payload}}"
          echo "${{matrix.description}}"
          echo "$(<./local-action/action_tests/pull_request_test_payload.json )"
          ls ./local-action

      - name: Check for task failures
        shell: bash
        run: |
          cd local-action
          npm install
          ./action_tests/verify_trunk_execution_log.js
